### ISSUE TITLE
Add a property page to configure editor settings

### ISSUE THREAD

**Issue by aaubry** [aaubry/YamlDotNet.Editor#3]
It would be useful to be able to configure settings like indentation and associated file extensions. I don't know how this can be done, but maybe someone knows?

**Comment by madskristensen** [comment]
I can add that in a PR if you're interested? You won't be able to have a setting for what file types to treat as yaml without creating a complete editor factory. That's complete overkill IMO

**Comment by aaubry** [comment]
I have no idea of what is required for this. What I would really like would be to be able to specify to treat tabs as spaces for YAML files only. I use tabs everywhere, but YAML doesn't work well with tabs. This forces me to configure all text files to use spaces, but I don't like that.
I am interested in a PR, but I'd also like your opinion on this. Thanks

**Comment by madskristensen** [comment]
You could take over the TAB command and insert 4 spaces in the TextBuffer automatically. If YAML doesn't play nice with spaces, then why even have an option for them?

**Comment by madskristensen** [comment]
I've added a very small and simple command handler in the #8 pull requests that always inserts 4 spaces when the user hits TAB

**Comment by aaubry** [comment]
This should be good enough. I hope everybody is comfortable with 4 spaces, though.

**Comment by aaubry** [comment]
Unfortunately, intercepting the TAB command is not working as expected, because when text is selected, the TAB key is used to increase the indent of the selection. Also, Shift+TAB is used to decrease indent, but since it is not intercepted, it removes the amount of spaces configured for the editor (2 spaces with my settings).

**Comment by madskristensen** [comment]
What if this is rolled into the `Format Document` command?

**Comment by madskristensen** [comment]
This extension changes tabs to spaces automatically. It must be possible to use the same logic.

https://github.com/editorconfig/editorconfig-visualstudio

**Comment by enghch** [comment]
Even if the tool could just warn me when a tab was present or indentation was something other than 2 spaces, that would be hugely helpful. Then the Format Document command would be enough to get the problem fixed.

**Comment by aaubry** [comment]
@madskristensen Thanks for the tip! I checked that project to see how they did it and replaced the TAB interception by this - 4780672

**Comment by madskristensen** [comment]
That is brilliant! And it looks so easy :)

**Comment by madskristensen** [comment]
I've noticed that you no longer push every build to vsixgallery.com. The purpose of vsixgallery.com is to host nightly builds - not to substitute the real VS Gallery. It's up to you of course if you don't want to push nightlies.

**Comment by aaubry** [comment]
I push every build from the master branch. Builds on the release branch are not pushed because anything that goes to release went to master first. Does this make sense?

**Comment by madskristensen** [comment]
yes, of course. I missed that part

**Comment by aaubry** [comment]
It is my fault, the build script should be clearer. It is just that testing the builds on AppVeyor is a pain because I need to commit every time and the builds take forever.
