### ISSUE TITLE
Unable to install version 1.4.1

### ISSUE THREAD

**Issue by xt0rted** [aaubry/YamlDotNet.Editor#4]
I just tried to update from 1.4.0 to 1.4.1 and received the same error as reported here https://github.com/madskristensen/WebEssentials2013/pull/1751

**Comment by aaubry** [comment]
I have released an [updated version](https://visualstudiogallery.msdn.microsoft.com/34423c06-f756-4721-8394-bc3d23b91ca7) that attempts to fix this issue. I cannot test it because I do not have Visual Studio 2015 CTP installed.
Can you test it and report if it works?

**Comment by xt0rted** [comment]
Looks like it worked, I was just able to update to v1.5.1

**Comment by aaubry** [comment]
Good. Thanks for testing!
