### ISSUE TITLE
Better name and description

### ISSUE THREAD

**Issue by madskristensen** [aaubry/YamlDotNet.Editor#9]
I would suggest renaming the extension to `YAML Editor`. The name is a little cryptic right now and doesn't reflect very well what it is. Also, the description could be more flashy and say something like `Provides a complete YAML editing experience in Visual Studio` or something to that effect.

Have high quality images (see PR #8), naming and descriptions makes a huge difference for your download count.

Also, perhaps update the Gallery page with more screenshots and a list of features that your extension provides, including links to create issues and/or suggest features etc.

**Comment by madskristensen** [comment]
I wonder if this image might be better as the extension icon? https://www.iconfinder.com/icons/315454/document_file_yml_icon#size=128

I think it definitely show more accurately that the extension adds a full YAML document editing experience. If you'd like, I can send a PR with it?

**Comment by aaubry** [comment]
I think you are right. I created this extension because I needed to work with YAML files, but I never imagined that other people would actually use it. I should polish these details. Thanks a lot for the suggestions and feedback!

**Comment by madskristensen** [comment]
Dude, the editor rocks. I'm surprised you didn't think people were gonna use it :)

**Comment by aaubry** [comment]
I have updated the name, description and icon, as per your suggestion. There should be more details and screenshots in the description, but it is already better.
